spring:
  application:
    name: currency-rate-service

cloud:
  eureka-host: ${EUREKA_HOST}

server:
  port: 8085

currency:
  client:
    url: "https://www.cbr.ru/scripts/XML_daily.asp"

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka/