spring:
  application:
    name: currency-rate-service

  config:
    import: optional:file:.env[.properties]

server:
  port: 8085

currency:
  client:
    url: "https://www.cbr.ru/scripts/XML_daily.asp"

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/